name: expert-seg
dependencies:
  - python=3.11
  - gputil=1.4.0
  - matplotlib=3.8.0
  - numpy=1.23.5
  - pandas=2.1.1
  - pip
  - porespy=2.4.2
  - prettytable=3.9.0
  - py-xgboost-gpu=1.7.6
  - scikit-image=0.22.0
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - tifffile=2023.9.26
  - pip:
    - myst-parser==2.0.0
    - sphinx_rtd_theme==2.0.0
    - xgboost=2.1.4
    - structure-tensor=0.2.0
    - torch=2.1.0
    - opencv-python=4.8.1
    - sphinx=7.2.6
    - furo==2024.01.29
    - cupy-cuda12x